name: build-and-e2e
on:
  push:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:
jobs:
  build_and_e2e:
    name: Build, Test, and E2E Fluentd Plugin
    runs-on: ubuntu-latest
    environment: build
    timeout-minutes: 30
    permissions:
      checks: write
      pull-requests: write
      id-token: write
      contents: read
    env:
      ENDPOINT: ${{ secrets.ENDPOINT }}
      TEST_DATABASE_NAME: ${{ secrets.TEST_DATABASE_NAME }}
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      TENANT_ID: ${{ secrets.TENANT_ID }}
      MANAGED_IDENTITY_CLIENT_ID: ${{ secrets.MANAGED_IDENTITY_CLIENT_ID }}
    steps:
      - name: Configure Kusto auth for User Assigned Managed Identity
        run: |
          echo "AUTH_TYPE=user_managed_identity" >> $GITHUB_ENV
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
          cache-version: 1
          
      - name: Configure bundler
        run: |
          bundle config set --local frozen false
          bundle config set --local deployment false
          
      - name: Install dependencies
        run: bundle install
        working-directory: .
        
      - name: Run unit tests
        run: bundle exec rake test TEST="test/plugin/test_out_kusto_*.rb"
        working-directory: .
        timeout-minutes: 10
        
      - name: Build gem
        run: gem build azure-kusto-fluentd.gemspec
        working-directory: .
        
      - name: Install Fluentd
        run: gem install fluentd
        
      - name: Install plugin
        run: gem install azure-kusto-fluentd-*.gem
        
      - name: Run e2e
        run: bundle exec rake test TEST="test/plugin/test_e2e_kusto.rb"
        working-directory: .
        timeout-minutes: 15
        continue-on-error: true
      - name: Publish Unit Test Results 
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            **/test-results.xml
            **/rspec.xml
            **/TEST-*.xml
