name: build-and-e2e
on:
  push:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:
jobs:
  build_and_e2e:
    name: Build, Test, and E2E Fluentd Plugin
    runs-on: [self-hosted, linux, azure-mi]
    environment: build
    permissions:
      checks: write
      pull-requests: write
      id-token: write
      contents: read
    env:
      ENDPOINT: ${{ secrets.ENDPOINT }}
      TEST_DATABASE_NAME: ${{ secrets.TEST_DATABASE_NAME }}
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      TENANT_ID: ${{ secrets.TENANT_ID }}
      MANAGED_IDENTITY_CLIENT_ID: ${{ secrets.MANAGED_IDENTITY_CLIENT_ID }}
    steps:
      - name: Configure Kusto auth for User Assigned Managed Identity
        run: |
          echo "AUTH_TYPE=user_managed_identity" >> $GITHUB_ENV
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
      - name: Install dependencies
        run: bundle install
        working-directory: .
      - name: Run unit tests
        run: bundle exec rake test TEST="test/plugin/test_out_kusto_*.rb"
        working-directory: .
      - name: Build gem
        run: gem build azure-kusto-fluentd.gemspec
        working-directory: .
      - name: Install Fluentd
        run: gem install fluentd
      - name: Install plugin
        run: gem install azure-kusto-fluentd-*.gem
      - name: Run e2e
        run: bundle exec rake test TEST="test/plugin/test_e2e_kusto.rb"
        working-directory: .
      - name: Publish Unit Test Results 
        uses: EnricoMi/publish-unit-test-result-action@v1.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: rspec.xml
